### ISSUE TITLE
Request for further details on code and data

### ISSUE THREAD

**Issue by rj678** [prgumd/SeaDroneSim2#2]
thank you for releasing this amazing repo! (@akshajgaur )

 I've opened this issue to request further clarification on the following - it'd help me greatly if you could point me to:

1. the dataset that you've made available, as mentioned in your paper "Whale Detection Enhancement through
Synthetic Satellite Images"

2. the code where you generate the Whale , esp configuring the species - I don't see a script for this

3. the code used for training and validation of the UNet or FPN as mentioned in your paper, so I can reproduce the results

4. any further details to reproduce Table 1 results would be very helpful

---------------------------

- minor clarification on page 5: in the second to last paragraph, you mention "networks have learned to recognize oysters ..." - I'm guessing that's a typo, and should be whales

I hope you think this request is reasonable - this is a very exciting project - I look forward to hearing back soon

**Comment by luuckiest** [comment]
We are trying our best to release the data and the code. Due to some unforeseen circumstances, it might take a bit longer.

**Comment by luuckiest** [comment]
Edited the readme with a colab and link for the real dataset.

**Comment by valentijnvenus** [comment]
@luuckiest may you check again, seems the links in the colab are not accessible:

E.g.
whale_coco_blender_2000.zip
whale_coco_real.zip

See suggestions below.

Thanks!


Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=13JEHQTsQMqpg_4T_oRAqBV3sXblC1EVw

but Gdown can't. Please check connections and permissions.
unzip:  cannot find or open /content/whale_coco_blender_2000.zip, /content/whale_coco_blender_2000.zip.zip or /content/whale_coco_blender_2000.zip.ZIP.
Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=10v2mONt1dNcNpp2G1YohDUVA_gouqskW

but Gdown can't. Please check connections and permissions.
unzip:  cannot find or open /content/whale_coco_real.zip, /content/whale_coco_real.zip.zip or /content/whale_coco_real.zip.ZIP.
