### ISSUE TITLE
Github link

### ISSUE THREAD

**Issue by henrysun9074** [prgumd/SeaDroneSim2#3]
The link to clone the repo https://github.com/akshajgaur/ocean-sim.git doesn't work. Is there a different one to use?

**Comment by rj678** [comment]
Hi @henrysun9074 - could you share the error you're getting - I was able to do `git clone https://github.com/prgumd/SeaDroneSim2.git`

**Comment by henrysun9074** [comment]
Ah, I was cloning the wrong repo link. Thank you!

**Comment by rj678** [comment]
no worries at all - lemme know if you make any progress with this repo - I opened this issue and have not heard back from the authors:

https://github.com/prgumd/SeaDroneSim2/issues/2

this is very interesting work and I'd like to reproduce the results in the paper - thank you and good luck!

**Comment by henrysun9074** [comment]
Yes, I am also working on doing something similar except using generative models for training data. This paper is a fascinating start! Do let me know if you find anything interesting/different. Thanks again :D
