### ISSUE TITLE
ImportError: cannot import name 'delete_plane' from 'SeaDroneSim2.src.plane' 

### ISSUE THREAD

**Issue by leesj0531** [prgumd/SeaDroneSim2#4]
Hello,

First of all, thank you very much for sharing your excellent research results. 
While working on using the technology, I encountered the following error message. Could it be due to a change in the code version? If you have any suggestions for resolving this issue, I would greatly appreciate it.

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[14], line 11
      7     sys.path.append(dir )
     10 from SeaDroneSim2.src.water import Water
---> 11 from SeaDroneSim2.src.plane import create_plane, delete_plane
     12 from SeaDroneSim2.src.waves import Waves
     14 def create_sim(mat, geo, size): 

ImportError: cannot import name 'delete_plane' from 'SeaDroneSim2.src.plane' (C:\Users\SJLEE\AI\test_v1\SeaDroneSim2\SeaDroneSim2\src\plane.py)
```

**Comment by luuckiest** [comment]
You might want to try it without delete_plane, I think it is a function that we used internally. We will update the code soon.
